//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEALS
    {
        public int ID_DEAL { get; set; }
        public Nullable<int> ID_REAL { get; set; }
        public Nullable<int> ID_CLIENT { get; set; }
        public Nullable<int> ID_PROPOSAL { get; set; }
        public Nullable<System.DateTime> DATA_DEALS { get; set; }
        public Nullable<decimal> COMM_REAL { get; set; }
    
        public virtual PEOPLE PEOPLE { get; set; }
        public virtual PEOPLE PEOPLE1 { get; set; }
        public virtual PROPOSALS PROPOSALS { get; set; }
    }
}
