//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSALS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPOSALS()
        {
            this.DEALS = new HashSet<DEALS>();
        }
    
        public int ID_PROPOSAL { get; set; }
        public Nullable<int> ID_SELLER { get; set; }
        public Nullable<int> ID_TYPE_OBJECT { get; set; }
        public Nullable<int> ID_AREA { get; set; }
        public string STREET { get; set; }
        public Nullable<int> FLAT { get; set; }
        public Nullable<int> FLOOR { get; set; }
        public Nullable<int> COUNT_FLOORS { get; set; }
        public Nullable<int> COUNT_ROOMS { get; set; }
        public Nullable<int> TOTAL_AREA { get; set; }
        public Nullable<int> LIVING_AREA { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> COST { get; set; }
    
        public virtual AREAS AREAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEALS> DEALS { get; set; }
        public virtual PEOPLE PEOPLE { get; set; }
        public virtual TYPE_OBJECTS TYPE_OBJECTS { get; set; }
    }
}
